# -*- coding: utf-8 -*-
"""Assingment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eR0MAZfbAvnqTMa_T5fcy7X5Ey5P4A9x
"""

import numpy as np
from scipy.stats import uniform
from matplotlib import pyplot as plt
uniform_data = np.linspace(0,1,100000)
plot1 = plt.figure(1)
fx = uniform.pdf(uniform_data,0,1)
plt.plot(uniform_data,fx)
plt.title("Probability density function of U:")
plt.xlabel("$u$")
plt.ylabel("$f_u$")
plot2 = plt.figure(2)
x = np.linspace(0,10,100000)
plt.plot(x,1-np.exp(-x/2))
plt.title("CDF of random variable X :")
plt.xlabel("$x$")
plt.ylabel("$F_X(x)$")
plot3 = plt.figure(3)
plt.plot(x,np.exp(-x/2)/2)
plt.title("Probability density function of X:")
plt.xlabel("$X$")
plt.ylabel("$f_x$")